version: '3'
services:
  mysql:
    image: mariadb:10.4.7
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 13306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  cafeteria-manage-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/cafeteria/run.sh
      - ./cafeteria-manage-api/build/libs:/home/cafeteria/libs
    ports:
      - 8080:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/cafeteria && sh run.sh"
  cafeteria-manage-web:
    image: node:10.16.3
    volumes:
      - ./cafeteria-manage-web:/home/cafeteria
    ports:
      - 3333:3000
    command: bash -c "cd /home/cafeteria && npm run dev"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10