spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/cafeteria
    username: root
    password: cafeteria
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---

spring:
  profiles: develop
  datasource:
    url: jdbc:h2:~/data/cafeteria
