spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---

spring:
  profiles: develop
  datasource:
    url: jdbc:h2:~/data/cafeteria
    username: sa
    password:
